"""empty message

Revision ID: 1318c2cb492c
Revises: 
Create Date: 2020-02-17 00:43:37.811371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1318c2cb492c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'role_id')
    # ### end Alembic commands ###
